name: Deploy Docs and DAS Variant to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create .npmrc
        run: |
          echo "@jeppesen-foreflight:registry=https://${{ vars.NPM_REGISTRY_URL }}/" >> .npmrc
          echo "//${{ vars.NPM_REGISTRY_URL }}/:_authToken=${{ secrets.GN_GITHUB_TOKEN }}" >> .npmrc
          echo "Created the following .npmrc:"; cat .npmrc

      # Install Node
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install dependencies
      - name: Install dependencies
        run: npm ci
      - name: Install gh-pages CLI
        run: npm install -g gh-pages

      # Build main docs
      - name: Build main docs
        run: npm run build

      # Build DAS variant, sending its output to a separate folder
      - name: Build DAS docs
  #     run: npm run build --configuration=das --output-path=das-dist
        run: npm run build:original:gh && npm run build:das:gh && gh-pages -d dist/dls-global-docs/browser -b gh-pages-original -e original && gh-pages -d dist-das/dls-global-docs/browser -b gh-pages-original -e das

      # Prepare deployment folder
      - name: Prepare publish directory
        run: |
          mkdir publish
          cp -r dist/* publish/
          cp -r das-dist publish/das

      # Deploy
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages