name: Deploy Docs and DAS Variant to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Create .npmrc
        run: |
          echo "@jeppesen-foreflight:registry=https://${{ vars.NPM_REGISTRY_URL }}/" >> .npmrc
          echo "//${{ vars.NPM_REGISTRY_URL }}/:_authToken=${{ secrets.GN_GITHUB_TOKEN }}" >> .npmrc
          echo "Created the following .npmrc:"; cat .npmrc

      # Install Node
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Build both projects
      - name: Build original docs
        run: npm run build:original:gh

      - name: Build DAS docs
        run: npm run build:das:gh

      # Prepare deployment folder
      - name: Prepare publish directory
        run: |
          mkdir -p publish/original
          mkdir -p publish/das
          cp -r dist/browser/* publish/original/
          cp -r dist-das/browser/* publish/das/

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./publish

      # Deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4